### ISSUE TITLE
How can i get text value from tags?

### ISSUE THREAD

**Issue by squuman** [yashaka/python-web-test#27]
How can i get text value from h1 tag?
What's method i should use?

**Comment by yashaka** [comment]
```python
from selene.support.shared import browser
from selene import query

element = browser.element('label')
text = element.get(query.text)
```

or

```python
from selene.support.shared import browser

element = browser.element('label')
webelement = element()
'''
# or
webelement = element.locate()
'''

text = webelement.text
```

**Comment by squuman** [comment]
Thx

**Comment by squuman** [comment]
> ```python
> from selene.support.shared import browser
> from selene import query
> 
> element = browser.element('label')
> text = element.get(query.text)
> ```
> 
> or
> 
> ```python
> from selene.support.shared import browser
> 
> element = browser.element('label')
> webelement = element()
> '''
> # or
> webelement = element.locate()
> '''
> 
> text = webelement.text
> ```

thx

**Comment by squuman** [comment]
@yashaka thx
